import { ref } from 'vue';

const Projects = ref([
    { year: '2025', month: '09', partner: '밀크파워텍', name: '센스허브(SennseHub) 넥태그 납품' },
    { year: '2025', month: '09', partner: '㈜농협정보시스템', name: '농협중앙회 2025년 IT경영혁신국 도급인력 운영' },
    { year: '2025', month: '09', partner: '㈜데이터쿡', name: '2025년 종합교육연수원 홈페이지 유지관리 및 운영지원' },
    { year: '2025', month: '09', partner: '㈜신세계아이앤씨', name: '[신세계백화점] 차세대 시스템 고도화(계약관리임대정산 고도화)' },
    { year: '2025', month: '08', partner: '㈜핸드위치', name: 'NH농협은행 그룹데이터 통합·활용 인프라 구축_포탈' },
    { year: '2025', month: '08', partner: '㈜유엔아워스', name: 'NH멤버스 오픈API 플랫폼 구축' },
    { year: '2025', month: '08', partner: '㈜핑거', name: '농협 (은행)2025년도 NH임베디드 기업뱅킹 플랫폼' },
    { year: '2025', month: '07', partner: '교보디티에스주식회사', name: 'NH농협생명 농.축협 맞춤형 AI가입설계 시스템 구축' },
    { year: '2025', month: '06', partner: '㈜신세계아이앤씨', name: '신세계라이브쇼핑 모바일/PC 부분 취소 프로젝트' },
    { year: '2025', month: '06', partner: '㈜농협정보시스템', name: '(중앙회)디지털 영농특화 플랫폼 고도화(오늘농사4단계)' },
    { year: '2025', month: '04', partner: '㈜아이티센엔텍', name: 'IBK기업은행 카드앱 상시운영반 운영업무 위탁 계약' },
    { year: '2025', month: '03', partner: '㈜신세계아이앤씨', name: '[신세계라이브쇼핑] AI기반 상품정보 고도화 프로젝트' },
    { year: '2025', month: '02', partner: '㈜펜타에스', name: '우리은행 IT자산관리시스템 구축 2단계 프로젝트' },
    { year: '2025', month: '01', partner: '㈜신세계아이앤씨', name: '신세계라이브쇼핑 운영시스템 개선' },
    { year: '2025', month: '01', partner: '㈜농협정보시스템', name: '농협중앙회 업무 위탁 운영 인력풀 활용 계약(자금)' },
    { year: '2025', month: '01', partner: '㈜농협정보시스템', name: '소비유통시스템 IT업무 위탁계약서(스마트워크)' },
    { year: '2025', month: '01', partner: '㈜농협정보시스템', name: '소비유통시스템 업무운영 도급계약(2025) (채권,채무,세무)' },
    { year: '2025', month: '01', partner: '볼보그룹코리아(주)', name: '영업관리시스템(TSM(SAS)) 유지보수' },
    { year: '2025', month: '01', partner: '볼보그룹코리아(주)', name: '콜센터 관리시스템 유지보수' },
    { year: '2025', month: '01', partner: '㈜농협정보시스템', name: '(중앙회) IT디지털정보단 도급인력 운영' },
    { year: '2025', month: '01', partner: '㈜농협정보시스템', name: '디지털금융 및 IT상시개발지원 인력운영(디지털금융)' },
    { year: '2024', month: '11', partner: '㈜신세계아이앤씨', name: '[RE]신세계백화점 차세대 시스템 구축 사업' },
    { year: '2024', month: '01', partner: '㈜SK', name: '농협은행 주식회사 NH농협(은행) 오픈뱅킹 확대 구축' },
    { year: '2024', month: '01', partner: '㈜농협정보시스템', name: '농협중앙회 2024년 IT경영혁신국 도급인력 운영' },
    { year: '2024', month: '09', partner: '㈜농협정보시스템', name: '(중앙회)전속 및 공통관리비 정산시스템 고도화' },
    { year: '2024', month: '09', partner: '㈜다름', name: '(B2C통합)NICE BizINFO 개편 개발' },
    { year: '2024', month: '08', partner: '㈜농협정보시스템', name: '소비유통시스템 IT업무 위탁계약(B부문)' },
    { year: '2024', month: '08', partner: '㈜농협정보시스템', name: '(경제지주)소비유통시스템 업무운영 도급계약(2024)(B부문)' },
    { year: '2024', month: '08', partner: '㈜신세계아이앤씨', name: '신세계백화점 기간계 현황 진단' },
    { year: '2024', month: '08', partner: '㈜펜타에스', name: '우리은행 IT자산관리시스템 구축 1단계 프로젝트' },
    { year: '2024', month: '05', partner: 'SK(주)', name: '농협은행 주식회사 클라우드 전환에 따른 기업뱅킹 개편 구축' },
    { year: '2024', month: '01', partner: '(주)엘지씨엔에스', name: 'SGI서울보증 차세대 시스템 구축_SGI-M 대응개발 구축' },
    { year: '2024', month: '01', partner: '㈜농협정보시스템', name: '온라인복권 자금관리시스템 운영(2024년)' },
    { year: '2024', month: '01', partner: '㈜농협정보시스템', name: '2024년도 IT디지털정보단 도급인력 운영' },
    { year: '2024', month: '01', partner: '볼보그룹코리아', name: '볼보그룹코리아(주)-영업관리시스템(TSM(SAS)) 유지보수' },
    { year: '2024', month: '01', partner: '볼보그룹코리아', name: '볼보그룹코리아(주)-콜센터 관리시스템 유지보수' },
    { year: '2024', month: '01', partner: '㈜신세계아이앤씨', name: '[신세계라이브쇼핑] 24년도 운영시스템 개선 [모바일시스템]' },
    { year: '2023', month: '12', partner: '㈜엘지씨엔에스', name: '농협은행IT본부 NH농협카드 통합 디지털 플랫폼 구축' },
    { year: '2023', month: '09', partner: '㈜농협정보시스템', name: '농협중앙회 2023년 IT경영혁신국 도급인력 운영' },
    { year: '2023', month: '09', partner: '㈜신세계아이앤씨', name: '[신세계푸드] 푸딩오피스 기능개선' },
    { year: '2023', month: '09', partner: '㈜신세계아이앤씨', name: '[신세계라이브쇼핑] 배송정책 개선 프로젝트' },
    { year: '2023', month: '09', partner: '㈜농협정보시스템', name: '(공통)2023년 디지털금융 도급인력 운영' },
    { year: '2023', month: '08', partner: 'SK㈜', name: 'NH농협(은행) 디지털금융 플랫폼 전환(전자금융)' },
    { year: '2023', month: '06', partner: '㈜신세계아이앤씨', name: '23년도 신세계라이브쇼핑 운영시스템 개선(하반기)' },
    { year: '2023', month: '03', partner: '㈜딥브레인에이아이', name: '딥브레인에이아이 내부 프로젝트' },
    { year: '2023', month: '02', partner: '㈜신세계아이앤씨', name: '셀픽시스템 고도화' },
    { year: '2023', month: '01', partner: '볼보그룹코리아', name: '볼보그룹코리아(주)-영업관리시스템(TSM(SAS)) 유지보수' },
    { year: '2023', month: '01', partner: '볼보그룹코리아', name: '볼보그룹코리아(주)-콜센터 관리시스템 유지보수' },
    { year: '2023', month: '01', partner: '㈜농협정보시스템', name: '2023년도 IT디지털정보단 도급인력 운영' },
    { year: '2023', month: '01', partner: '㈜농협정보시스템', name: '2023년도 IT디지털정보단 도급인력 운영 용역(도급)' },
    { year: '2022', month: '12', partner: '㈜신한디에스', name: '현대백화점카드 차세대 시스템 구축' },
    { year: '2022', month: '11', partner: '㈜신세계아이앤씨', name: '[신세계라이브쇼핑] SSG(이마트몰) 신규입점 및 제휴 구조 개선' },
    { year: '2022', month: '11', partner: '㈜신세계아이앤씨', name: '[샤넬코리아] 시스템개발 [E-RETAILER 멤버십 재구축]' },
    { year: '2022', month: '01', partner: '㈜농협정보시스템', name: '농협중앙회 2022년 IT신기술혁신국 도급인력 운영' },
    { year: '2022', month: '09', partner: '㈜농협정보시스템', name: '(공통)2022년 디지털금융 도급인력 운영' },
    { year: '2022', month: '08', partner: '이와이컨설팅', name: '신세계백화점 차세대시스템 구축' },
    { year: '2022', month: '06', partner: '㈜농협정보시스템', name: '상호금융 차세대 디지털금융 전략수립' },
    { year: '2022', month: '05', partner: '한국농수산식품유통공사', name: '공급식품플랫폼(SeaT) 유지관리 위탁운영 용역' },
    { year: '2022', month: '05', partner: '㈜신세계아이앤씨', name: '모바일쇼핑 네이티브 App 고도화' },
    { year: '2022', month: '05', partner: '㈜농협정보시스템', name: '상호금융 NH콕마이데이터2.0 자산관리 고도화' },
    { year: '2022', month: '04', partner: '㈜신세계아이앤씨', name: 'goodMD 서비스 개선 개발계약' },
    { year: '2022', month: '04', partner: '㈜신세계아이앤씨', name: '[자산] SELLPICK 서비스 고도화' },
    { year: '2022', month: '03', partner: '㈜농협정보시스템', name: '차세대 경제유통 시스템 구축(경제/유통 부문/스마트워크부문)' },
    { year: '2022', month: '03', partner: '네파 주식회사', name: '네파 샤방넷 제휴 연계' },
    { year: '2022', month: '01', partner: '㈜신세계아이앤씨', name: '[신세계]백화점 FIT PAY SSG.com 연동 개발' },
    { year: '2022', month: '01', partner: 'SK주식회사', name: 'CJ대한통운 차세대 택배시스템 구축' },
    { year: '2022', month: '01', partner: '㈜농협정보시스템', name: 'IT상호금융부 도급인력 운영 - NH콕팜 개발부문' },
    { year: '2022', month: '01', partner: '㈜농협정보시스템', name: '농협중앙회 IT신기술혁신국 도급인력 운영(급여정보시스템)' },
    { year: '2022', month: '01', partner: '뱅크웨어글로벌㈜', name: '상호금융 마이데이터 및 개인자산관리 부문 ITO_서비스 채널 개발 운영' },
    { year: '2022', month: '01', partner: '볼보그룹코리아', name: 'SASKR E-Document개발 외 신규 개발' },
    { year: '2022', month: '01', partner: '볼보그룹코리아', name: '영업관리시스템(TSM(SAS)) 유지보수' },
    { year: '2022', month: '01', partner: '볼보그룹코리아', name: '콜센터 관리시스템 유지보수' },
    { year: '2021', month: '12', partner: '㈜제뉴파인', name: '신한은행 퇴직연금 통합플랫폼 고도화' },
    { year: '2021', month: '11', partner: '㈜아스템즈', name: '[스타벅스] 성과급 시스템화' },
    { year: '2021', month: '01', partner: '다음정보기술', name: '배전자동화통신망 통합관리시스템 구축 WEB GIS 엔진 재개발' },
    { year: '2021', month: '09', partner: '㈜신세계아이앤씨', name: 'SELLPICK 샤넬코리아 e-Biz efficiency solution 구축' },
    { year: '2021', month: '09', partner: '㈜농협정보시스템', name: '(공통)2021년 디지털금융 도급인력 운영' },
    { year: '2021', month: '08', partner: '㈜핑거', name: '(공통)2021년 디지털금융 도급인력 운영' },
    { year: '2021', month: '07', partner: '㈜농협정보시스템', name: '농협 경제 스마트워크 시스템 고도화 구축' },
    { year: '2021', month: '07', partner: '㈜디리아', name: '신한은행 THE NEXT시스템 코어디지털 기반 구축 용역계약' },
    { year: '2021', month: '07', partner: '㈜아스템즈', name: '[스타벅스] 온디맨드 고도화(업무시스템)[영업정보]' },
    { year: '2021', month: '06', partner: '㈜인젠트', name: '한국투자저축은행 통합 모바일앱ODS 프로젝트' },
    { year: '2021', month: '06', partner: '㈜신세계아이앤씨', name: '스타벅스 기프티콘 발급 개발' },
    { year: '2021', month: '06', partner: '㈜신세계아이앤씨', name: '[네파] IT Outsourcing ERP유지보수' },
    { year: '2021', month: '05', partner: '㈜엔디에스', name: '공공급식 통합시스템구축(심사관리)' },
    { year: '2021', month: '05', partner: '㈜윈위즈', name: 'BGF 경영효율화 프로젝트' },
    { year: '2021', month: '05', partner: '㈜핑거', name: '국민은행_마이데이터_서비스,포탈,대응개발' },
    { year: '2021', month: '05', partner: '㈜농협정보시스템', name: '중앙회 위탁 업무 인력풀 활용 계약 (급여정보시스템 개선)' },
    { year: '2021', month: '04', partner: '㈜신세계아이앤씨', name: '[백화점]VIP라운지 온라인 음료 주문 개발[통합고객시스템 개발]' },
    { year: '2021', month: '04', partner: '㈜핑거', name: '농협은행 올원뱅크 2021 생활금융플랫폼화 개발추진' },
    { year: '2021', month: '04', partner: '㈜신세계아이앤씨', name: '자산 goodMD 고도화' },
    { year: '2021', month: '04', partner: '㈜신세계아이앤씨', name: 'JAJU 리뉴얼 CRM 수정 개발' },
    { year: '2021', month: '04', partner: '㈜신세계아이앤씨', name: '신세계프라퍼티 셀픽 추가개발' },
    { year: '2021', month: '04', partner: '㈜신세계아이앤씨', name: '스타일난다 API 인터페이스 개발' },
    { year: '2021', month: '04', partner: '㈜신세계아이앤씨', name: 'eCvan 서비스 개선' },
    { year: '2021', month: '03', partner: '㈜뱅크웨어글로벌', name: '농협중앙회 상호금융 마이데이터 플랫폼 구축_PFM 고도화' },
    { year: '2021', month: '02', partner: '㈜우리카드', name: '우리카드 위비멤버스 리뉴얼 구축' },
    { year: '2021', month: '01', partner: '㈜농협정보시스템', name: '금융지주 연결결산시스템 분리 구축' },
    { year: '2020', month: '12', partner: '㈜아스템즈', name: 'Ondemand(배달서비스)외 다수 프로젝트' },
    { year: '2020', month: '11', partner: '㈜농협정보시스템', name: '농협중앙회 교육정보시스템 재구축 사업' },
    { year: '2020', month: '11', partner: '㈜신세계아이앤씨', name: '스타벅스코리아 PPMS 전형 고도화' },
    { year: '2020', month: '11', partner: '㈜엘지씨엔에스', name: '금융보안원 금융분야 마이데이터 테스트베드시스템 구축' },
    { year: '2020', month: '11', partner: '롯데정보통신㈜', name: 'NH멤버스 정보계 및 마케팅시스템 구축' },
    { year: '2020', month: '01', partner: '㈜누리어시스템', name: 'NH농협손해보험 비대면 서비스 고도화 개발' },
    { year: '2020', month: '01', partner: '㈜농협정보시스템', name: '농협홍삼 종합정보시스템 재구축' },
    { year: '2020', month: '01', partner: '㈜아스템즈', name: '스타벅스코리아 PDA 시스템 구축 및 재고실사 통합 프로젝트' },
    { year: '2020', month: '01', partner: '㈜신세계아이앤씨', name: '신세계푸드 미착상품관리 고도화 개발' },
    { year: '2020', month: '09', partner: '㈜농협정보시스템', name: '농협중앙회 IT신기술혁신국 도급인력 운영(급여정보시스템)' },
    { year: '2020', month: '09', partner: '㈜신세계아이앤씨', name: '신세계면세점 PDA 시스템 구축' },
    { year: '2020', month: '09', partner: '㈜농협정보시스템', name: '농협상호금융 콕팜 도급인력 운영' },
    { year: '2020', month: '09', partner: '㈜농협정보시스템', name: '농협은행 디지털금융 도급인력 운영' },
    { year: '2020', month: '09', partner: '씨제이씨지브이㈜', name: 'CGV 모바일 앱 운영' },
    { year: '2020', month: '08', partner: '㈜농협정보시스템', name: '농협상호금융 비대면 개인자산관리서비스 구축(채널부문)' },
    { year: '2020', month: '08', partner: '㈜엔디에스', name: '농협목우촌 차세대시스템(모바일부문)' },
    { year: '2020', month: '07', partner: '㈜신세계아이앤씨', name: '신세계티비쇼핑 제휴몰(네이버스마트스토아,AK몰) 연계 개발' },
    { year: '2020', month: '06', partner: '㈜농협정보시스템', name: '농협상호금융 콕팜 4.0 고도화 구축' },
    { year: '2020', month: '05', partner: '㈜신세계아이앤씨', name: '네파 IT Outsourcing - ERP 유지보수' },
    { year: '2020', month: '05', partner: '㈜신세계아이앤씨', name: '신세계 특정(비단품) 단품관리 프로젝트(영업정보시스템개발)' },
    { year: '2020', month: '04', partner: '㈜농협정보시스템', name: '농협경제지주 전속 및 공통관리비 정산 시스템 구축' },
    { year: '2020', month: '04', partner: '㈜피앤피컨설팅', name: 'NH농협손해보험 애플리케이션 위탁 운영' },
    { year: '2020', month: '04', partner: '㈜신세계아이앤씨', name: '신세계인터네셔널 매장지원 통합시스템 POG 추가 개발' },
    { year: '2020', month: '04', partner: '㈜신세계아이앤씨', name: '네파 매장 가입 프로세스 전산화 개발' },
    { year: '2020', month: '03', partner: '㈜신세계아이앤씨', name: '신세계티비쇼핑 VOD제작 스케줄관리시스템 개발' },
    { year: '2020', month: '03', partner: '㈜신세계아이앤씨', name: '신세계백화점 시코르 운영시스템 구축' },
    { year: '2020', month: '03', partner: '㈜신세계아이앤씨', name: '신세계인터네셔널 매장지원 통합시스템 구축' },
    { year: '2020', month: '02', partner: '㈜모든솔루션', name: '농협목우촌 차세대시스템 구축(용역)' },
    { year: '2020', month: '02', partner: '㈜신세계아이앤씨', name: '신세계엘앤비 영업정보시스템 개선 프로젝트' },
    { year: '2020', month: '01', partner: '㈜엔디에스', name: '농협목우촌 차세대시스템' },
    { year: '2020', month: '01', partner: '한국아이비엠㈜', name: '현대커머셜 CDF 시스템 구축 서비스' },
    { year: '2020', month: '01', partner: '볼보트럭코리아㈜', name: '콜센터 시스템 유지보수' },
    { year: '2020', month: '01', partner: '볼보트럭코리아㈜', name: '영업 관리시스템(SAS) 유지보수' },
    { year: '2020', month: '01', partner: '㈜신세계아이앤씨', name: '신세계푸드 가금류 이력제관리 등 LEGACY 개선 개발' },
    { year: '2019', month: '09', partner: '㈜농협정보시스템', name: '농협상호금융 서비스종합시스템의 마켓Me-in시스템 內 이전 개발' },
    { year: '2019', month: '09', partner: '㈜농협정보시스템', name: 'NH멤버스 앱 고도화(2019)' },
    { year: '2019', month: '09', partner: '㈜농협정보시스템', name: '농협은행 디지털 금융 도급인력 운영' },
    { year: '2019', month: '09', partner: '㈜농협정보시스템', name: '농협상호금융 콕팜 도급인력 운영' },
    { year: '2019', month: '08', partner: '㈜다우기술', name: '키움증권 ERP시스템 재무회계시스템 개발' },
    { year: '2019', month: '07', partner: '㈜농협정보시스템', name: '농축협 우선출자시스템 재구축' },
    { year: '2019', month: '06', partner: '㈜핑거', name: '농협은행 2019년 올원뱅크 고도화' },
    { year: '2019', month: '06', partner: '㈜신세계아이앤씨', name: '신세계백화점 뷰티플랫폼 기간계 개선 구축' },
    { year: '2019', month: '06', partner: '농협정보시스템', name: '농협상호금융 콕팜 3.0 고도화 구축' },
    { year: '2019', month: '06', partner: '㈜크레디트라인', name: '농협카드 본인확인서비스 연계기관 이중화 개발' },
    { year: '2019', month: '05', partner: '㈜모든솔루션', name: '농협중앙회 조합원관리 시스템 재구축' },
    { year: '2019', month: '05', partner: '농협정보시스템', name: '농협은행 디지털금융 서비스 및 보안 고도화 구축 프로젝트' },
    { year: '2019', month: '05', partner: '㈜신세계아이앤씨', name: '신세계백화점 ESL 확대 적용 개발 건(스마트허브EDI운영정보)' },
    { year: '2019', month: '05', partner: '㈜신세계아이앤씨', name: '신세계백화점 블러섬 APP 내 업무 개선' },
    { year: '2019', month: '03', partner: '㈜아스템즈', name: '롯데푸드(주) 엘푸드 시스템 개발' },
    { year: '2019', month: '01', partner: '㈜커머스웨어', name: '신세계TV쇼핑 제휴몰 개발' },
    { year: '2019', month: '01', partner: '농협정보시스템', name: '농협은행 온라인복권 자금관리시스템 운영' },
    { year: '2019', month: '01', partner: '㈜아스템즈', name: '스타벅스 디지털 메뉴보드 시스템 구축' },
    { year: '2019', month: '01', partner: '㈜인포뱅크', name: '삼성카드 커뮤니티 앱 서비스 운영' },
    { year: '2019', month: '01', partner: '㈜다우기술', name: '키움증권_ERP시스템_구축' },
    { year: '2019', month: '01', partner: '농협정보시스템', name: '농협은행 디지털 금융 도급인력 운영(전자금융AP 개발부문)' },
    { year: '2019', month: '01', partner: '농협정보시스템', name: '농협은행 디지털 금융 도급인력 운영(PC 개발부문)' },
    { year: '2019', month: '01', partner: '㈜신세계아이앤씨', name: '신세계티비쇼핑 2019년 정보시스템 유지보수 계약' },
    { year: '2019', month: '01', partner: '벤츠그룹코리아㈜', name: 'Maintenance and Component' },
    { year: '2018', month: '12', partner: '한국아이비엠㈜', name: '신세계이마트 에브리데이 물류시스템 구축' },
    { year: '2018', month: '12', partner: '유니웹스㈜', name: '제주항공 유료맴버십, 라운지이용권' },
    { year: '2018', month: '12', partner: '유니웹스㈜', name: '제주항공 간단손해보험 개발' },
    { year: '2018', month: '12', partner: '㈜아스템즈', name: '스타벅스 STORE365 기능개선 외 유지보수' },
    { year: '2018', month: '12', partner: '볼보그룹코리아㈜', name: '볼보그룹코리아(주)-영업관리시스템(TSM(SAS)) 유지보수' },
    { year: '2018', month: '12', partner: '볼보그룹코리아㈜', name: '볼보그룹코리아(주)-콜센터 관리시스템 유지보수' },
    { year: '2018', month: '11', partner: '㈜핑거', name: '농협은행 (공통)디지털 금융 도급인력 운영(모바일 개발부문)' },
    { year: '2018', month: '01', partner: '한국아이비엠㈜', name: '모던하우스 무역수출입 시스템 개발' },
    { year: '2018', month: '01', partner: '농협정보시스템', name: '농협은행 디지털 금융 및 상호금융 콕팜 도급인력 운영(전자금융AP)' },
    { year: '2018', month: '01', partner: '농협정보시스템', name: '농협은행 디지털금융 및 상호금융 콕팜 도급인력 운영(상호금융 콕팜)' },
    { year: '2018', month: '01', partner: '㈜아스템즈', name: '신세계백화점 스마트 허브 시스템 고도화' },
    { year: '2018', month: '09', partner: '다임러트럭코리아', name: '벤츠그룹코리아 RAS Oracle Migration to MSSQL' },
    { year: '2018', month: '09', partner: '한국아이비엠㈜', name: '모던하우스 발주 생산관리 및 고객관리 서비스 구축' },
    { year: '2018', month: '09', partner: '㈜다우기술', name: '키움증권_ERP시스템 구축' },
    { year: '2018', month: '08', partner: '㈜아스템즈', name: '신세계이마트 캐셔근무 시스템 구축 프로젝트' },
    { year: '2018', month: '07', partner: '농협정보시스템', name: '농협은행 나눔로또 운영 및 유지보수' },
    { year: '2018', month: '07', partner: '㈜핑거', name: '농협은행 2018년 올원뱅크고도화 구축' },
    { year: '2018', month: '07', partner: '㈜농협은행', name: '농협은행 (공동)2018년 금융상품마켓 고도화 개발' },
    { year: '2018', month: '06', partner: '농축협조합', name: '농협중앙회 지역 농축협 인력관리시스템 재구축' },
    { year: '2018', month: '06', partner: '홈플러스', name: '홈플러스 GHS+ 유지보수 용역' },
    { year: '2018', month: '05', partner: '㈜신세계티비쇼핑', name: '신세계티비쇼핑 정보시스템 유지보수 계약' },
    { year: '2018', month: '05', partner: '㈜농협은행', name: '농협은행 2018년 디지털금융 고도화 구축' },
    { year: '2018', month: '04', partner: '홈플러스', name: '특약매입시스템 구축' },
    { year: '2018', month: '04', partner: '롯데정보통신', name: '개발 표준 프레임워크 구축 프로젝트' },
    { year: '2018', month: '04', partner: '벤츠그룹코리아㈜', name: '벤츠그룹코리아 BPA Vulnerability Mitigation Support' },
    { year: '2018', month: '04', partner: '벤츠그룹코리아㈜', name: '벤츠코리아 홈페이지 유지보수' },
    { year: '2018', month: '03', partner: '롯데카드', name: '롯데카드 LP프로젝트 용역' },
    { year: '2018', month: '03', partner: '벤츠그룹코리아(주)', name: '벤츠그룹코리아 CVS 프로그램 개발' },
    { year: '2018', month: '02', partner: '농협정보시스템', name: '농협식품 종합정보시스템 구축' },
    { year: '2018', month: '01', partner: '볼보그룹코리아(주)', name: 'SAS KR 고도화 및 CBGS연계 전자세금계산서 연계 개발' },
    { year: '2018', month: '01', partner: '롯데정보통신', name: '롯데맴버쉽 운영 용역 계약' },
    { year: '2018', month: '01', partner: '웰컴저축은행', name: '웰컴저축은행중고차할부 용역 계약' },
    { year: '2018', month: '01', partner: '삼성카드', name: '삼성카드 복지몰(블루베리)Renewal 시스템 개발·공급 계약' },
    { year: '2018', month: '01', partner: '우리카드', name: '우리카드 운영업무 도급 용역' },
    { year: '2018', month: '01', partner: '(주)오씨에스코리아', name: '홈페이지 유지보수 계약' },
    { year: '2018', month: '01', partner: '다임러트럭코리아', name: '영업관리시스템(RAS) 유지보수' },
    { year: '2018', month: '01', partner: '다임러트럭코리아', name: 'RAS Maintenance Service Jan' },
    { year: '2018', month: '01', partner: '스타벅스코리아', name: '스타벅스 SCM고도화 프로젝트' },
    { year: '2018', month: '01', partner: '삼성카드', name: '삼성카드 신복지 APP 개발' },
    { year: '2017', month: '12', partner: '볼보그룹코리아(주)', name: '볼보그룹코리아_콜센터관리시스템_유지보수' },
    { year: '2017', month: '12', partner: '볼보그룹코리아(주)', name: '영업관리시스템(TSM(SAS)) 유지보수' },
    { year: '2017', month: '11', partner: '농협정보시스템', name: '농협식품 종합정보시스템 개발' },
    { year: '2017', month: '11', partner: '농협정보시스템', name: '농협하나로유통 마트장비 쇼핑몰 시스템 구축' },
    { year: '2017', month: '11', partner: '스타벅스코리아', name: '스타벅스 2017년 POS 기능개선 외' },
    { year: '2017', month: '01', partner: '삼성카드', name: '삼성카드 ITO APP 운영계약 (기본앱, 앱카드, 다이렉트오토, taptap카드)' },
    { year: '2017', month: '01', partner: '스타벅스코리아', name: '무제한 문자MMS발송 프로젝트 계약' },
    { year: '2017', month: '01', partner: '스카니아코리아(주)', name: 'SMS 개선 사업' },
    { year: '2017', month: '01', partner: '볼보그룹코리아(주)', name: '자동배정기능개선' },
    { year: '2017', month: '01', partner: '삼성카드', name: '삼성카드 복지몰(블루베리)Renewal 시스템 개발·공급 계약' },
    { year: '2017', month: '01', partner: '삼성카드', name: '삼성카드 ITO Ios운영개발·공급 계약' },
    { year: '2017', month: '09', partner: '볼보그룹코리아(주)', name: 'RAS EPA Development for Daimler Trucks Korea' },
    { year: '2017', month: '09', partner: 'NDS', name: '농협사료 신인사급여 정보시스템 구축' },
    { year: '2017', month: '09', partner: '스타벅스코리아', name: '스타벅스 자유토론방 개선 및 머그 브라보 조회' },
    { year: '2017', month: '09', partner: '스타벅스코리아', name: '스타벅스 유지보수시스템 개선사업' },
    { year: '2017', month: '09', partner: '스타벅스코리아', name: '보령메디앙스 차세대 POS / PRM 시스템 구축' },
    { year: '2017', month: '08', partner: '삼성카드', name: '삼성카드 모바일쿠폰, 웰컴쿠폰 시스템 개발' },
    { year: '2017', month: '08', partner: '스타벅스코리아', name: '스타벅스 SSG PAY 계좌결제 수단 추가 개발 및 알리페이 연동' },
    { year: '2017', month: '08', partner: '스타벅스코리아', name: '스타벅스 DM365 시스템 구축' },
    { year: '2017', month: '07', partner: '스타벅스코리아', name: '스타벅스 엑사데이터 테스트 및 B2B ARS 결제 추가' },
    { year: '2017', month: '07', partner: '스타벅스코리아', name: '스타벅스 DM365 프로젝트/유지보수 개선사업' },
    { year: '2017', month: '06', partner: '㈜LG전자', name: '㈜LG전자 New Best 프로젝트 문자발송 관리업무 구축' },
    { year: '2017', month: '06', partner: '볼보그룹코리아(주)', name: '볼보 레포팅 솔루션 구축' },
    { year: '2017', month: '06', partner: '농협정보시스템', name: '농협하나로유통 식품자회사 설립 전산시스템 ASP 구축' },
    { year: '2017', month: '06', partner: '스타벅스코리아', name: '근태세분화 및 물품형 Gift 프로젝트 외 개발' },
    { year: '2017', month: '05', partner: '신세계백화점', name: '신세계백화점 협력사원지원시스템 출입증 관리 업무 개선 개발' },
    { year: '2017', month: '05', partner: '스타벅스코리아', name: '스타벅스 DM365 모바일 시스템 구축' },
    { year: '2017', month: '03', partner: '스타벅스코리아', name: '스타벅스 시스템 DB암호화 개발' },
    { year: '2017', month: '03', partner: '스타벅스코리아', name: '스타벅스 DM365 프로젝트 설계 및 기획' },
    { year: '2017', month: '02', partner: '삼성카드', name: '삼성카드 전대환대출 APP 고도화 개발' },
    { year: '2017', month: '02', partner: '스타벅스코리아', name: '스타벅스 모바일 스케쥴링 및 5BE CARD 프로젝트' },
    { year: '2017', month: '02', partner: '스타벅스코리아', name: '스타벅스 근태세분화 및 장애인 WH 개선 프로젝트' },
    { year: '2017', month: '02', partner: '볼보그룹코리아㈜', name: '영업관리시스템(SAS) 통합 유지보수' },
    { year: '2017', month: '02', partner: '볼보그룹코리아㈜', name: '콜센터 관리시스템 통합 유지보수' },
    { year: '2017', month: '02', partner: '다임러트럭코리아㈜', name: 'MBCV시스템 통합유지보수' },
    { year: '2017', month: '01', partner: '스타벅스코리아', name: '스타벅스 DID 시스템 개발 기획 및 설계' },
    { year: '2017', month: '01', partner: '㈜아스템즈', name: '신세계면세점 DF 고도화 개발' },
    { year: '2017', month: '01', partner: '다임러트럭코리아㈜', name: 'MBCV시스템 RAS Encryption' },
    { year: '2016', month: '12', partner: '스타벅스코리아', name: '스타벅스 유지보수 시스템 기능 개선 및 B2B ARS 결재 도입' },
    { year: '2016', month: '11', partner: '스타벅스코리아', name: '스타벅스 전자영수증 및 쿠폰 개발' },
    { year: '2016', month: '11', partner: '한국예선업협동조합', name: '도선 및 예선 정보시스템 정보연계를 위한 시스템 개발' },
    { year: '2016', month: '11', partner: '㈜아스템즈', name: '신세계백화점 스마트허브 시스템 고도화' },
    { year: '2016', month: '01', partner: '볼보그룹코리아㈜', name: '영업관리시스템(SAS) 통합 유지보수' },
    { year: '2016', month: '01', partner: '볼보그룹코리아㈜', name: '콜센터 관리시스템 통합 유지보수' },
    { year: '2016', month: '01', partner: '다임러트럭코리아㈜', name: 'MBCV시스템 통합유지보수' },
    { year: '2016', month: '01', partner: '㈜태창항업', name: '울산도선 통합 유지보수' },
    { year: '2016', month: '01', partner: '㈜송도도선', name: '송도도선 통합 유지보수' },
    { year: '2016', month: '09', partner: '㈜퓨처젠', name: '신세계백화점 협력사 지원시스템 구축' },
  ]
);

export default Projects
