import { ref } from 'vue';

const banks = ref([
    {
        "compCd": "01",
        "moduleCd": "ACMA",
        "commonGrp": "003",
        "commonCd": "01",
        "commonNm": "비씨카드",
        "refVal1": null,
        "refVal2": null,
        "refVal3": null,
        "refVal4": null,
        "refVal5": null
    },
    {
        "compCd": "01",
        "moduleCd": "ACMA",
        "commonGrp": "003",
        "commonCd": "02",
        "commonNm": "KB국민카드",
        "refVal1": null,
        "refVal2": null,
        "refVal3": null,
        "refVal4": null,
        "refVal5": null
    },
    {
        "compCd": "01",
        "moduleCd": "ACMA",
        "commonGrp": "003",
        "commonCd": "03",
        "commonNm": "하나(외환)카드",
        "refVal1": null,
        "refVal2": null,
        "refVal3": null,
        "refVal4": null,
        "refVal5": null
    },
    {
        "compCd": "01",
        "moduleCd": "ACMA",
        "commonGrp": "003",
        "commonCd": "04",
        "commonNm": "삼성카드",
        "refVal1": null,
        "refVal2": null,
        "refVal3": null,
        "refVal4": null,
        "refVal5": null
    },
    {
        "compCd": "01",
        "moduleCd": "ACMA",
        "commonGrp": "003",
        "commonCd": "06",
        "commonNm": "신한카드",
        "refVal1": null,
        "refVal2": null,
        "refVal3": null,
        "refVal4": null,
        "refVal5": null
    },
    {
        "compCd": "01",
        "moduleCd": "ACMA",
        "commonGrp": "003",
        "commonCd": "07",
        "commonNm": "현대카드",
        "refVal1": null,
        "refVal2": null,
        "refVal3": null,
        "refVal4": null,
        "refVal5": null
    },
    {
        "compCd": "01",
        "moduleCd": "ACMA",
        "commonGrp": "003",
        "commonCd": "08",
        "commonNm": "롯데카드",
        "refVal1": null,
        "refVal2": null,
        "refVal3": null,
        "refVal4": null,
        "refVal5": null
    },
    {
        "compCd": "01",
        "moduleCd": "ACMA",
        "commonGrp": "003",
        "commonCd": "09",
        "commonNm": "한미카드",
        "refVal1": null,
        "refVal2": null,
        "refVal3": null,
        "refVal4": null,
        "refVal5": null
    },
    {
        "compCd": "01",
        "moduleCd": "ACMA",
        "commonGrp": "003",
        "commonCd": "10",
        "commonNm": "신세계한미카드",
        "refVal1": null,
        "refVal2": null,
        "refVal3": null,
        "refVal4": null,
        "refVal5": null
    },
    {
        "compCd": "01",
        "moduleCd": "ACMA",
        "commonGrp": "003",
        "commonCd": "11",
        "commonNm": "씨티카드",
        "refVal1": null,
        "refVal2": null,
        "refVal3": null,
        "refVal4": null,
        "refVal5": null
    },
    {
        "compCd": "01",
        "moduleCd": "ACMA",
        "commonGrp": "003",
        "commonCd": "12",
        "commonNm": "NH채움카드",
        "refVal1": null,
        "refVal2": null,
        "refVal3": null,
        "refVal4": null,
        "refVal5": null
    },
    {
        "compCd": "01",
        "moduleCd": "ACMA",
        "commonGrp": "003",
        "commonCd": "13",
        "commonNm": "수협카드",
        "refVal1": null,
        "refVal2": null,
        "refVal3": null,
        "refVal4": null,
        "refVal5": null
    },
    {
        "compCd": "01",
        "moduleCd": "ACMA",
        "commonGrp": "003",
        "commonCd": "14",
        "commonNm": "신협카드",
        "refVal1": null,
        "refVal2": null,
        "refVal3": null,
        "refVal4": null,
        "refVal5": null
    },
    {
        "compCd": "01",
        "moduleCd": "ACMA",
        "commonGrp": "003",
        "commonCd": "15",
        "commonNm": "우리BC카드",
        "refVal1": null,
        "refVal2": null,
        "refVal3": null,
        "refVal4": null,
        "refVal5": null
    },
    {
        "compCd": "01",
        "moduleCd": "ACMA",
        "commonGrp": "003",
        "commonCd": "16",
        "commonNm": "하나카드",
        "refVal1": null,
        "refVal2": null,
        "refVal3": null,
        "refVal4": null,
        "refVal5": null
    },
    {
        "compCd": "01",
        "moduleCd": "ACMA",
        "commonGrp": "003",
        "commonCd": "17",
        "commonNm": "우리카드",
        "refVal1": null,
        "refVal2": null,
        "refVal3": null,
        "refVal4": null,
        "refVal5": null
    },
    {
        "compCd": "01",
        "moduleCd": "ACMA",
        "commonGrp": "003",
        "commonCd": "21",
        "commonNm": "광주카드",
        "refVal1": null,
        "refVal2": null,
        "refVal3": null,
        "refVal4": null,
        "refVal5": null
    },
    {
        "compCd": "01",
        "moduleCd": "ACMA",
        "commonGrp": "003",
        "commonCd": "22",
        "commonNm": "전북카드",
        "refVal1": null,
        "refVal2": null,
        "refVal3": null,
        "refVal4": null,
        "refVal5": null
    },
    {
        "compCd": "01",
        "moduleCd": "ACMA",
        "commonGrp": "003",
        "commonCd": "23",
        "commonNm": "제주카드",
        "refVal1": null,
        "refVal2": null,
        "refVal3": null,
        "refVal4": null,
        "refVal5": null
    },
    {
        "compCd": "01",
        "moduleCd": "ACMA",
        "commonGrp": "003",
        "commonCd": "24",
        "commonNm": "산은캐피탈",
        "refVal1": null,
        "refVal2": null,
        "refVal3": null,
        "refVal4": null,
        "refVal5": null
    },
    {
        "compCd": "01",
        "moduleCd": "ACMA",
        "commonGrp": "003",
        "commonCd": "25",
        "commonNm": "해외비자",
        "refVal1": null,
        "refVal2": null,
        "refVal3": null,
        "refVal4": null,
        "refVal5": null
    },
    {
        "compCd": "01",
        "moduleCd": "ACMA",
        "commonGrp": "003",
        "commonCd": "26",
        "commonNm": "해외마스터",
        "refVal1": null,
        "refVal2": null,
        "refVal3": null,
        "refVal4": null,
        "refVal5": null
    },
    {
        "compCd": "01",
        "moduleCd": "ACMA",
        "commonGrp": "003",
        "commonCd": "27",
        "commonNm": "해외다이너스",
        "refVal1": null,
        "refVal2": null,
        "refVal3": null,
        "refVal4": null,
        "refVal5": null
    },
    {
        "compCd": "01",
        "moduleCd": "ACMA",
        "commonGrp": "003",
        "commonCd": "28",
        "commonNm": "해외AMX",
        "refVal1": null,
        "refVal2": null,
        "refVal3": null,
        "refVal4": null,
        "refVal5": null
    },
    {
        "compCd": "01",
        "moduleCd": "ACMA",
        "commonGrp": "003",
        "commonCd": "29",
        "commonNm": "해외JCB",
        "refVal1": null,
        "refVal2": null,
        "refVal3": null,
        "refVal4": null,
        "refVal5": null
    },
    {
        "compCd": "01",
        "moduleCd": "ACMA",
        "commonGrp": "003",
        "commonCd": "31",
        "commonNm": "SK-OKCashBag",
        "refVal1": null,
        "refVal2": null,
        "refVal3": null,
        "refVal4": null,
        "refVal5": null
    },
    {
        "compCd": "01",
        "moduleCd": "ACMA",
        "commonGrp": "003",
        "commonCd": "32",
        "commonNm": "우체국",
        "refVal1": null,
        "refVal2": null,
        "refVal3": null,
        "refVal4": null,
        "refVal5": null
    },
    {
        "compCd": "01",
        "moduleCd": "ACMA",
        "commonGrp": "003",
        "commonCd": "33",
        "commonNm": "저축은행",
        "refVal1": null,
        "refVal2": null,
        "refVal3": null,
        "refVal4": null,
        "refVal5": null
    },
    {
        "compCd": "01",
        "moduleCd": "ACMA",
        "commonGrp": "003",
        "commonCd": "34",
        "commonNm": "은련",
        "refVal1": null,
        "refVal2": null,
        "refVal3": null,
        "refVal4": null,
        "refVal5": null
    },
    {
        "compCd": "01",
        "moduleCd": "ACMA",
        "commonGrp": "003",
        "commonCd": "35",
        "commonNm": "새마을금고",
        "refVal1": null,
        "refVal2": null,
        "refVal3": null,
        "refVal4": null,
        "refVal5": null
    },
    {
        "compCd": "01",
        "moduleCd": "ACMA",
        "commonGrp": "003",
        "commonCd": "36",
        "commonNm": "KDB산업",
        "refVal1": null,
        "refVal2": null,
        "refVal3": null,
        "refVal4": null,
        "refVal5": null
    },
    {
        "compCd": "01",
        "moduleCd": "ACMA",
        "commonGrp": "003",
        "commonCd": "37",
        "commonNm": "카카오뱅크",
        "refVal1": null,
        "refVal2": null,
        "refVal3": null,
        "refVal4": null,
        "refVal5": null
    },
    {
        "compCd": "01",
        "moduleCd": "ACMA",
        "commonGrp": "003",
        "commonCd": "38",
        "commonNm": "케이뱅크",
        "refVal1": null,
        "refVal2": null,
        "refVal3": null,
        "refVal4": null,
        "refVal5": null
    },
    {
        "compCd": "01",
        "moduleCd": "ACMA",
        "commonGrp": "003",
        "commonCd": "39",
        "commonNm": "PAYCO포인트",
        "refVal1": null,
        "refVal2": null,
        "refVal3": null,
        "refVal4": null,
        "refVal5": null
    },
    {
        "compCd": "01",
        "moduleCd": "ACMA",
        "commonGrp": "003",
        "commonCd": "40",
        "commonNm": "카카오머니",
        "refVal1": null,
        "refVal2": null,
        "refVal3": null,
        "refVal4": null,
        "refVal5": null
    },
    {
        "compCd": "01",
        "moduleCd": "ACMA",
        "commonGrp": "003",
        "commonCd": "41",
        "commonNm": "SSG머니",
        "refVal1": null,
        "refVal2": null,
        "refVal3": null,
        "refVal4": null,
        "refVal5": null
    },
    {
        "compCd": "01",
        "moduleCd": "ACMA",
        "commonGrp": "003",
        "commonCd": "42",
        "commonNm": "네이버페이포인트",
        "refVal1": null,
        "refVal2": null,
        "refVal3": null,
        "refVal4": null,
        "refVal5": null
    },
    {
        "compCd": "01",
        "moduleCd": "ACMA",
        "commonGrp": "003",
        "commonCd": "44",
        "commonNm": "토스뱅크",
        "refVal1": null,
        "refVal2": null,
        "refVal3": null,
        "refVal4": null,
        "refVal5": null
    },
    {
        "compCd": "01",
        "moduleCd": "ACMA",
        "commonGrp": "003",
        "commonCd": "46",
        "commonNm": "토스머니",
        "refVal1": null,
        "refVal2": null,
        "refVal3": null,
        "refVal4": null,
        "refVal5": null
    }
]);

const paymentType = ref([
    {
        "compCd": "01",
        "moduleCd": "ACMA",
        "commonGrp": "002",
        "commonCd": "01",
        "commonNm": "야근식대",
        "refVal1": null,
        "refVal2": null,
        "refVal3": null,
        "refVal4": null,
        "refVal5": null
    },
    {
        "compCd": "01",
        "moduleCd": "ACMA",
        "commonGrp": "002",
        "commonCd": "02",
        "commonNm": "프로젝트관리비",
        "refVal1": null,
        "refVal2": null,
        "refVal3": null,
        "refVal4": null,
        "refVal5": null
    },
    {
        "compCd": "01",
        "moduleCd": "ACMA",
        "commonGrp": "002",
        "commonCd": "03",
        "commonNm": "야근교통비",
        "refVal1": null,
        "refVal2": null,
        "refVal3": null,
        "refVal4": null,
        "refVal5": null
    },
    {
        "compCd": "01",
        "moduleCd": "ACMA",
        "commonGrp": "002",
        "commonCd": "04",
        "commonNm": "복리후생비",
        "refVal1": null,
        "refVal2": null,
        "refVal3": null,
        "refVal4": null,
        "refVal5": null
    },
    {
        "compCd": "01",
        "moduleCd": "ACMA",
        "commonGrp": "002",
        "commonCd": "05",
        "commonNm": "차량유지비",
        "refVal1": null,
        "refVal2": null,
        "refVal3": null,
        "refVal4": null,
        "refVal5": null
    },
    {
        "compCd": "01",
        "moduleCd": "ACMA",
        "commonGrp": "002",
        "commonCd": "06",
        "commonNm": "회의비",
        "refVal1": null,
        "refVal2": null,
        "refVal3": null,
        "refVal4": null,
        "refVal5": null
    },
    {
        "compCd": "01",
        "moduleCd": "ACMA",
        "commonGrp": "002",
        "commonCd": "07",
        "commonNm": "기타관리비",
        "refVal1": null,
        "refVal2": null,
        "refVal3": null,
        "refVal4": null,
        "refVal5": null
    },
    {
        "compCd": "01",
        "moduleCd": "ACMA",
        "commonGrp": "002",
        "commonCd": "08",
        "commonNm": "전산장비구매액",
        "refVal1": null,
        "refVal2": null,
        "refVal3": null,
        "refVal4": null,
        "refVal5": null
    },
    {
        "compCd": "01",
        "moduleCd": "ACMA",
        "commonGrp": "002",
        "commonCd": "09",
        "commonNm": "장비임대료",
        "refVal1": null,
        "refVal2": null,
        "refVal3": null,
        "refVal4": null,
        "refVal5": null
    },
    {
        "compCd": "01",
        "moduleCd": "ACMA",
        "commonGrp": "002",
        "commonCd": "10",
        "commonNm": "사무실임대료",
        "refVal1": null,
        "refVal2": null,
        "refVal3": null,
        "refVal4": null,
        "refVal5": null
    },
    {
        "compCd": "01",
        "moduleCd": "ACMA",
        "commonGrp": "002",
        "commonCd": "11",
        "commonNm": "교육훈련비",
        "refVal1": null,
        "refVal2": null,
        "refVal3": null,
        "refVal4": null,
        "refVal5": null
    },
    {
        "compCd": "01",
        "moduleCd": "ACMA",
        "commonGrp": "002",
        "commonCd": "12",
        "commonNm": "소모품비",
        "refVal1": null,
        "refVal2": null,
        "refVal3": null,
        "refVal4": null,
        "refVal5": null
    },
    {
        "compCd": "01",
        "moduleCd": "ACMA",
        "commonGrp": "002",
        "commonCd": "13",
        "commonNm": "도서인쇄비",
        "refVal1": null,
        "refVal2": null,
        "refVal3": null,
        "refVal4": null,
        "refVal5": null
    },
    {
        "compCd": "01",
        "moduleCd": "ACMA",
        "commonGrp": "002",
        "commonCd": "14",
        "commonNm": "운반비",
        "refVal1": null,
        "refVal2": null,
        "refVal3": null,
        "refVal4": null,
        "refVal5": null
    }
]);

export { banks, paymentType };
